package com.example.techtask.model;
// default package
// Generated Feb 22, 2019 5:51:06 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Calculatedroutes generated by hbm2java
 */
@Entity
@Table(name = "calculatedroutes", catalog = "techtask")
public class CalculatedroutesEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "pk", unique = true, nullable = false)
	private Integer pk;
	
	@ManyToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name = "customer_fk")
	private CustomerEntity customerEntity;
	
	@ManyToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name = "depot_fk")
	private DepotEntity depotEntity;
	
	@ManyToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name = "store_fk")
	private StoreEntity storeEntity;
	
	@Column(name = "routeDistance", precision = 22, scale = 0)
	private Double routeDistance;

	public CalculatedroutesEntity() {
	}
	
	public CalculatedroutesEntity(int pk) {
		this.pk = pk;
	}

	public CalculatedroutesEntity(CustomerEntity customerEntity, DepotEntity depotEntity, StoreEntity storeEntity, Double routeDistance) {
		this.customerEntity = customerEntity;
		this.depotEntity = depotEntity;
		this.storeEntity = storeEntity;
		this.routeDistance = routeDistance;
	}

	
	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	
	public CustomerEntity getCustomer() {
		return this.customerEntity;
	}

	public void setCustomer(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}


	public DepotEntity getDepot() {
		return this.depotEntity;
	}

	public void setDepot(DepotEntity depotEntity) {
		this.depotEntity = depotEntity;
	}

	public StoreEntity getStore() {
		return this.storeEntity;
	}

	public void setStore(StoreEntity storeEntity) {
		this.storeEntity = storeEntity;
	}


	public Double getRouteDistance() {
		return this.routeDistance;
	}

	public void setRouteDistance(Double routeDistance) {
		this.routeDistance = routeDistance;
	}

}
