package com.example.techtask.model;
// default package
// Generated Feb 22, 2019 5:51:06 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Depot generated by hbm2java
 */
@Entity
@Table(name = "depot", catalog = "techtask")
public class DepotEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "pk", unique = true, nullable = false)
	private Integer pk;
	
	@Column(name = "name", length = 45)
	private String name;
	
	@Column(name = "longitude", precision = 22, scale = 0)
	private Double longitude;
	
	@Column(name = "latitude", precision = 22, scale = 0)
	private Double latitude;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depotEntity")
	private Set<CalculatedroutesEntity> calculatedroutes = new HashSet<CalculatedroutesEntity>(0);

	@Column(name = "availableDrones")
	private int availableDrones;
	
	public DepotEntity() {
	}
	
	public DepotEntity(int pk) {
		this.pk = pk;
	}

	public DepotEntity(String name, Double longitude, Double latitude, Set<CalculatedroutesEntity> calculatedrouteses, Integer availableDrones) {
		this.name = name;
		this.longitude = longitude;
		this.latitude = latitude;
		this.calculatedroutes = calculatedrouteses;
		this.availableDrones = availableDrones;
	}


	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Set<CalculatedroutesEntity> getCalculatedrouteses() {
		return this.calculatedroutes;
	}

	public void setCalculatedrouteses(Set<CalculatedroutesEntity> calculatedrouteses) {
		this.calculatedroutes = calculatedrouteses;
	}

	public int getAvailableDrones() {
		return this.availableDrones;
	}

	public void setAvailableDrones(int availableDrones) {
		this.availableDrones = availableDrones;
	}
}
