package com.example.techtask.model;
// default package
// Generated Feb 22, 2019 5:51:06 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods", catalog = "techtask")
public class GoodsEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "pk", unique = true, nullable = false)
	private Integer pk;
	
	@ManyToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name = "store_fk")
	private StoreEntity storeEntity;
	
	@Column(name = "name", length = 45)
	private String name;
	
	@Column(name = "amount")
	private Integer amount;

	public GoodsEntity() {
	}

	public GoodsEntity(int pk) {
		this.pk = pk;
	}
	public GoodsEntity(StoreEntity storeEntity, String name, Integer amount) {
		this.storeEntity = storeEntity;
		this.name = name;
		this.amount = amount;
	}

	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public StoreEntity getStore() {
		return this.storeEntity;
	}

	public void setStore(StoreEntity storeEntity) {
		this.storeEntity = storeEntity;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
